    # print(f' Média: {media_roubo_veiculo:.2f}')
    # print(f' Mediana: {mediana_roubo_veiculo:.2f}')
    # print(f' Distância: {distancia_media_mediana:.2f}')
    # print(f'Amplitude: {amplitude}')
    # print('Mínimo:', minimo)
    # print(f' Limite Inferior: {lim_inferior}')
    # print(f'Q1: {q1}')
    # print(f'Q2: {q2}')
    # print(f'Q3: {q3}')
    # print(f'IQR: {iqr}')
    # print(f' Limite Superior: {lim_superior}')
    # print('Máximo: ', maximo)